server:
    port: 8003
spring:
    application:
        name: client-service
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console
    kafka:
        #bootstrap-servers: localhost:9093
        #bootstrap-servers: 172.27.0.4:9092
        bootstrap-servers: localhost:9093
        consumer:
            group-id: client-group-id
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
kafka:
    producer:
        topic: Order
    consumer:
        topic: Notification

